// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mneudmicgsgrxjahdxgt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1uZXVkbWljZ3NncnhqYWhkeGd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NzAxNjIsImV4cCI6MjA2MTM0NjE2Mn0.H8xjHoGmYCNPfZXTrZbjyk9V29ysSNFQ7lA54wgBv_w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);